language: ruby
sudo: false
rvm:
    - 2.2.2
env:
    - DB=mysql
    - DB=postgresql
    - CODACY_PROJECT_TOKEN=ca837d25b0ac46e9975430b6ac12ac9d
branches:
    only:
        - master
services:
    - redis-server
script:
    - RAILS_ENV=test bundle exec rake db:schema:load --trace
    - bundle exec rake db:test:prepare
    - bundle exec rspec spec/
before_script:
    - cp config/database.travis.yml config/database.yml
    - cp config/secrets.example.yml config/secrets.yml
    - mysql -e 'create database trado_test_db'      
    - psql -c 'create database trado_test_db' -U postgres
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install bower -g
    - bower install