development:
  adapter: postgresql
  encoding: unicode
  database: trado_dev
  pool: 5
  username: tomdallimore
  password: 

  # MySQL example developemnt
  # adapter: mysql2
  # encoding: utf8
  # database: trado_dev
  # host: localhost
  # pool: 30
  # username: root
  # password:

test:
  adapter: postgresql
  encoding: unicode
  database: trado_test
  pool: 5
  username: tomdallimore
  password: 
  # adapter: mysql2
  # encoding: utf8
  # database: trado_test
  # host: localhost
  # pool: 30
  # username: root
  # password:


production:
  adapter: postgresql
  encoding: unicode
  database: trado
  pool: 5
  username: postgres
  password: admin

  # MySQL example production
  # adapter: mysql2
  # encoding: utf8
  # database: trado
  # host: localhost
  # pool: 30
  # username: root
  # password: password
  # socket: /var/run/mysqld/mysqld.sock
