development:
    secret_key_base: d9ac75015119e7603233e7b59c3b2af7562b8c014033739f9b4e42a365aa7a44d8c74525a2b6861f0c1cb9a6ec6437512fec76dbe7c646dccebf8b9e9bc05d51
    global_url: http://localhost:3000
    mailer_asset_url: http://localhost:3000
    asset_url: http://localhost:3000
    carrierwave_url: http://cdn1.tomdallimore.com
    redis_url: redis://localhost:6379/12
    mailer_server: smtp.example.com
    mailer_port: 587
    mailer_domain: localhost:3000
    mailer_user_name: me@example.com
    mailer_password: wkqndbdnwdjnq
    aws_s3_id: wkqndbdnwdjnq
    aws_s3_key: wkqndbdnwdjnq
    aws_s3_bucket: example-bucket
    aws_s3_region: eu-region-1
    rollbar_access_token: wkqndbdnwdjnq
test:
    secret_key_base: d9ac75015119e7603233e7b59c3b2af7562b8c014033739f9b4e42a365aa7a44d8c74525a2b6861f0c1cb9a6ec6437512fec76dbe7c646dccebf8b9e9bc05d51
    global_url: http://localhost:3000
    mailer_asset_url: http://localhost:3000
    asset_url: http://localhost:3000
    carrierwave_url: http://cdn1.tomdallimore.com
    redis_url: redis://localhost:6379/12
    mailer_server: smtp.example.com
    mailer_port: 587
    mailer_domain: localhost:3000
    mailer_user_name: me@example.com
    mailer_password: wkqndbdnwdjnq
    aws_s3_id: wkqndbdnwdjnq
    aws_s3_key: wkqndbdnwdjnq
    aws_s3_bucket: example-bucket
    aws_s3_region: eu-region-1
    rollbar_access_token: wkqndbdnwdjnq